### ISSUE TITLE
Issues with latest development branch version

### ISSUE THREAD

**Issue by PCAssistSoftware** [becerda/DiskpartGUI-WPF#44]
Hi

Thanks for making the changes

1) The Show Volume, Show Disk, Show Partitions buttons on the View menu don't seem to work.  But they do work on right click context menu

2) Disk number is not showing correct values - it shows 0 for all my volumes as per first screenshot

![image](https://user-images.githubusercontent.com/10872799/64770439-18f9e200-d545-11e9-9933-402a040449ab.png)

But should be more like this:-

![image](https://user-images.githubusercontent.com/10872799/64770508-375fdd80-d545-11e9-9eea-41fb9bd48c87.png)

**Comment by becerda** [comment]
Sorry its taken so long to get to this issue, I've been sick. I have pushed an update to development branch that includes a simple logger. If you could rerun the show volumes list and copy/past that logger here, I could better understand what is going on. The logger text file should be located at bin/Debug/DiskpartLogger.txt. Thanks!

Edit: The View menu items should be working now as well

**Comment by PCAssistSoftware** [comment]
No problem at all, hope you feel better now. Please find log attached. View menu now working fine

[DiskpartLogger.txt](https://github.com/becerda/DiskpartGUI-WPF/files/3615407/DiskpartLogger.txt)

**Comment by becerda** [comment]
So I've looked over the logger file you sent and compared it to what I've been getting. I noticed a big difference between the outputs.

Yours looks like:
> \>Volume 0 is the selected volume.
\>
\>There are no disks attached to this volume.
\>
\>Read-only              : No
\>Hidden                 : No
\>No Default Drive Letter: No
\>Shadow Copy            : No
\>Offline                : No
\>BitLocker Encrypted    : No
\>Installable            : No
\>

And the output I've been getting:
> \>Volume 0 is the selected volume.
\>
\>  Disk ###  Status         Size     Free     Dyn  Gpt
\>  --------  -------------  -------  -------  ---  ---
\>* Disk 0    Online          931 GB      0 B         
\>
\>Read-only              : No
\>Hidden                 : No
\>No Default Drive Letter: No
\>Shadow Copy            : No
\>Offline                : No
\>BitLocker Encrypted    : No
\>Installable            : Yes
\>
\>Volume Capacity        :  931 GB
\>Volume Free Space      :  752 GB

I was a bit concerned at first of why you weren't getting any disks attached to this volume and then I realized that your Volume 0 is the DVD drive, so of course there would be no disk attached.
>\>  Volume 0     D                       DVD-ROM         0 B  No Media

This issue was also happening if there was an unformatted partition or if there are no partitions on a disk. I have updated the regex once again and hopefully it fixes the issue. Please let me know if this is the case. Thanks.

**Comment by PCAssistSoftware** [comment]
Hi, sorry but still issues, this time it crashes on line 612 of DiskpartProcess.cs  

System.FormatException: 'Input string was not in a correct format.'

the value of gc["parentnumber"].Value at the time is ""

**Comment by becerda** [comment]
Ok, I think I got it this time. Did some more regex checks and hopefully it will fix this issue.

I also added an Advanced Logging setting which just enables/disables the appended information in the log file.

**Comment by PCAssistSoftware** [comment]
Hi, yes that now seems to work and show correct details

I do get one popup message though?

![image](https://user-images.githubusercontent.com/10872799/65503600-26a45580-debd-11e9-837d-6a3a5b86af63.png)

[DiskpartLogger.txt](https://github.com/becerda/DiskpartGUI-WPF/files/3646646/DiskpartLogger.txt)

**Comment by becerda** [comment]
This is happening because the regex, the way it was written, must match specific strings. I have updated the regex to be a bit more dynamic with what it finds. Also pushed more checks on the success of the matches which should help with error reduction.

Thanks for the reports!

**Comment by PCAssistSoftware** [comment]
I'm really sorry to report that I  still get an error :( 

screenshots and log below

![image](https://user-images.githubusercontent.com/10872799/65837666-25768c80-e2f2-11e9-883f-44c41be147e5.png)

![image](https://user-images.githubusercontent.com/10872799/65837670-36270280-e2f2-11e9-8166-4bf4ce6b8043.png)

[DiskpartLogger.txt](https://github.com/becerda/DiskpartGUI-WPF/files/3667937/DiskpartLogger.txt)

**Comment by becerda** [comment]
Missing some '(', should be good now, my bad...

**Comment by PCAssistSoftware** [comment]
Perfect!! great work - thank you

**Comment by becerda** [comment]
Thanks again for reporting the issue! Closing this thread now.
